language: python
python: 2.7
services:
  - mongodb
  - mysql
  - postgresql
  - docker

before_install:
  - sudo apt update -qq
  - sudo apt install python-dev python-libvirt libffi-dev libssl-dev
  - sudo apt install libpq-dev libmysqlclient-dev rar
  - sudo apt install libcairo2-dev libpng-dev libossp-uuid-dev
  - sudo apt install libfreerdp-dev libjpeg-turbo8-dev

    # Install guacd.
  - sudo docker pull guacamole/guacd
  - sudo docker run --rm --network host -d guacamole/guacd

  - sudo mysql -e "CREATE USER cuckoo@localhost IDENTIFIED BY 'cuckoo'"
  - sudo mysql -e "GRANT ALL PRIVILEGES ON * . * TO cuckoo@localhost"
  - sudo mysql -e "FLUSH PRIVILEGES"
  - sudo mysql -e "CREATE DATABASE cuckootest"
  - sudo mysql -e "CREATE DATABASE cuckootest060"
  - sudo mysql -e "CREATE DATABASE cuckootest11"
  - sudo mysql -e "CREATE DATABASE distcuckootest"
  - psql -U postgres -c "CREATE USER cuckoo WITH PASSWORD 'cuckoo'"
  - psql -U postgres -c "CREATE DATABASE cuckootest"
  - psql -U postgres -c "CREATE DATABASE cuckootest060"
  - psql -U postgres -c "CREATE DATABASE cuckootest11"
  - psql -U postgres -c "CREATE DATABASE distcuckootest"

  - sudo mysql -e "CREATE DATABASE cuckootestimport"
  - sudo mysql cuckootestimport < tests/files/sql/11my.sql
  - psql -U postgres -c "CREATE DATABASE cuckootestimport"
  - psql -U postgres cuckootestimport <tests/files/sql/11pg.sql >/dev/null
  - pip install psycopg2 mysql-python weasyprint==0.36

install:
  # Fetch monitor & stuff which is required for CWD migration tests.
  - python stuff/monitor.py

  # Bump the version of Cuckoo during tests (e.g., for new Signatures).
  - python stuff/patch_version.py setup.py 3.0

  - pip install -U pip setuptools
  - python setup.py sdist
  - pip install -e .
  - pip install pytest==4.6.9 pytest-cov codecov coveralls distorm3 pycrypto
  - pip install flask-testing mock pytest-django pytest-pythonpath responses

  # Install Volatility.
  - git clone https://github.com/volatilityfoundation/volatility vol-setup
  - cd vol-setup && python setup.py install && cd ..

script:
  # Create the Cuckoo Working Directory.
  - cuckoo -d

  # Download Cuckoo Signatures.
  - cuckoo community

  # Check the code integrity of the Signatures by running Cuckoo.
  - cuckoo -d --ignore-vuln 2>&1|grep "Unable to bind ResultServer"

  # Run tests from the "tests" directory.
  - pytest --cov=cuckoo

after_success:
  - coveralls
  - codecov

dist: bionic
